### ISSUE TITLE
deepar flutter plus package incompatibility with 16KB

### ISSUE THREAD

**Issue by mehrab-heidary** [Ifoegbu1/deepar-flutter-plus#9]
Your Flutter package does not match Google's guidelines and apps exported with your package cannot be published to the Google Store.
Because Google's recently released rules tell developers that apps submitted to us for publication must match the 16KB page size, otherwise their app will be rejected. I just wrote an app with Flutter for Android that uses the latest version of your package, but because you used old libraries in your package, during the output of your package, the developer's app does not support 16KB pages, and this problem must be solved by you by updating your package, and only you can solve this problem.

**Comment by Ifoegbu1** [comment]
Fixed in v0.2.1. Updated Android Gradle Plugin to 8.7.0, Gradle to 8.9, compileSdkVersion to 35, and added proper 16KB page size configuration. The package now meets Google Play Store requirements for 16KB page size compatibility.

**Comment by Emmy-lo** [comment]
For my app, this update still doesn't work. I tried uploading to the Play Store without this package and it says "accept 16 kb". But with this updated package the same warnings remained:
Does not support 16 KB

Libraries that do not support 16 KB:
base/lib/arm64-v8a/libnative-lib.so
base/lib/arm64-v8a/libtensorflowlite_c.so
base/lib/arm64-v8a/libtensorflowlite_gpu_delegate.so
base/lib/arm64-v8a/libxzimgSDK.so
base/lib/x86_64/libnative-lib.so


> Fixed in v0.2.1. Updated Android Gradle Plugin to 8.7.0, Gradle to 8.9, compileSdkVersion to 35, and added proper 16KB page size configuration. The package now meets Google Play Store requirements for 16KB page size compatibility.

**Comment by Ifoegbu1** [comment]
I'm looking into this
